services:
  db:
    image: postgres:15
    container_name: postgres_db_poc
    restart: always
    profiles:
      - db
    environment:
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
      POSTGRES_DB: poc
    ports:
      - "5444:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_admin_poc
    profiles:
      - db
    ports:
      - "8085:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=poc@poc.com
      - PGADMIN_DEFAULT_PASSWORD=poc
    depends_on:
      - db

  mcp-server:
    build: ./mcp-server
    container_name: mcp_server_poc
    restart: always
    profiles:
      - mcp
    ports:
      - "8000:8000"